### ISSUE TITLE
UnityAds.ane causes ApplicationVerificationFailed on AIR SDK 21

### ISSUE THREAD

**Issue by vforsh** [Heyzap/unityads-ane#3]
Hi,

I'm packaging iOS app with latest stable AIR SDK (version 21.0.0.198, Windows).

App can't be installed when I'm including UnityAds.ane in the build

I get **Installation Error: ApplicationVerificationFailed.**

Best,
Vladislav

**Comment by marchbold** [comment]
Probably not an issue with the ANE, AIR 20/21 has problems on windows correctly signing the application when using ANEs. 

Best solution is to use the current AIR 22 beta.

**Comment by vforsh** [comment]
Yes, this is what we do at the moment. Thanks to Adobe that beta 22 is stable and there are no major issues.
